language: ruby
rvm:
- 2.6.5
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
cache: bundler
before_install:
- sudo update-ca-certificates
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
install:
- bundle install
before_script:
- chmod +x script/cibuild
script: script/cibuild
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - JEKYLL_ENV=production
sudo: false
before_deploy: script/s3-deploy
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: nichenjie.com
  skip_cleanup: true
  region: ca-central-1
  local_dir: _site
  cache_control: max-age=31536000
