language: ruby
rvm:
- 2.6.5
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
cache: bundler
before_install:
- sudo update-ca-certificates
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
install:
- bundle install
before_script:
- chmod +x script/cibuild
script: script/cibuild
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - JEKYLL_ENV=production
  - secure: ZkAcKZhwpLLMeqPJAIz4UCgXts5DR2UeoxwH3f4mVopCYyx+KIkpjp+HPCXAJTlJMq5x2TxBVaLSKbvD2lf/bXsoiOzv5qXtv5vC4+D8vcOt4xmvkIO2GTr9/PXt6dqNsFETugKYMNIR1VMAuJbNK6Crqzgf6NfoWTdQ6TB6EuroeQE7P6roI2sCk2uhHaIS03oHvyNYUUajXrbzUCw0nedU1MF+SYDYmCv7q+k5TdyIabI4KPhN1jQClAawWxLnejSd+n9aBTBfAhWJi8MdGObdacX/5lujTqdYwL+jD0c4XkXccKG9FFA3HN9PGqpVS9UU1EhpvpzNTItv62/eBySNUKqH7dWeHvxUH3fiZtU1MyK8M+YJuBLSIv5Wp2yWBs9zZr51Rkik7rg39vbgCkZs+exDUs07vcnMTjafKScQOy+KBU5OkaLW4dTOj3y2rEYmSTeCBs8GQiytWN6t0M+a5HsypZUd6b5fr2ELbdwoF1dsUcMBM5RmBp+FapFaLtLSPNKChzzC67MW9T5SNUoTK4UzeLoVhcUj0/LW/BI1l/tofvEsMdRQN+Fi0CdkDO9WJJDHC3v+L/5KOyNSdRI3qLdHjNDlKuL3lpRmpBuUOVjnJ9qPaXkLCEKy9xytCyPXbLaXj40pQr5LXlYMeGIQRqn7z25F1ebnHu6vcII=
  - secure: E//zJ41vSM3tkWTYDIFIAYuDEeC8uZk/y5l5ZNqNWNQfFRHreGJMA7kv6jO3MIYLYnxmXGe7ilUU25Usr7un4QESLZYD0+/tl/01EF0EBY4U+hkVfP85eOMR7TPDWdsqK01auJYheORGVR4afM8fkm+O8PyG+M4n9rr3Mwd4j8c0pjsYc/7ZrSezk/Vjcf3uEFu43YD3WUyOFr4fK0LDLYfzXsVkQJnhkKBAklXVhlooRM+lqVO86FU2qyZtcsYXTQnMqLsxjlvr/IlO4EBo7mioExGOd4ljFLl84rX5Sb+tAtkEgDiC8HuXrwlma2wNGa0P/WnyeYrZgeY5+gjxddeDIDr4qTy2PYO4ojPDKIP4z6oVfcjfo6e8/wJ/kj+/kTcFelUt9fxL+RvOYYCMCV8dBAefxMfeLel0KSoRAykeNF79frksJ0iP9GnKQx+FpoU+Q21Ajv5JKQANM8ckQOk1n0V0UVjl50lx2td4tNml6B3cQgxKmKYhQFG1PAx0lfaTXur7o4Pa0nocudGXwuRwZXIaaILxt8KuK3wsQEgNWPlPBxwZBge5pyzq6krCVNVP/Ue3iX1rpA5AqU0cc+5FDX1J4ohgBsairUZ1UEtH9ebHi3KmPW69dkkQPdrC5yYhPdRvvSXpV1DS7R9NHf+iVtgwwx8ZCF04zOS4a8Q=
sudo: false
before_deploy: script/cibuild
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: nichenjie.com
  skip_cleanup: true
  region: ca-central-1
  local_dir: _site
  cache_control: max-age=31536000
