language: ruby

rvm:
  - 2.7.2

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

cache: bundler

before_install:
  - sudo update-ca-certificates

install:
  - bundle install

before_script:
  - chmod +x script/cibuild.sh

script: script/cibuild.sh

branches:
  only:
    - master
    
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JEKYLL_ENV=production

before_deploy:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - chmod +x script/empty-bucket.sh
  - script/empty-bucket.sh

deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    bucket: www.nichenjie.com
    skip_cleanup: true
    region: ap-east-1
    local_dir: _site
    cache_control: "public, max-age=31536000"

after_deploy:
  - chmod +x script/invalidate-cache.sh
  - script/invalidate-cache.sh
