source "https://rubygems.org"

gem "jekyll", "~> 3.5"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-feed"
gem "jemoji"
gem "jekyll-include-cache"
gem "jekyll-archives"
gem "minimal-mistakes-jekyll"
gem "html-proofer"
gem "rake"
gem "katex"
gem "execjs"